### ISSUE TITLE
Headers serialization

### ISSUE THREAD

**Issue by imp** [nox/hyper_serde#4]
Headers (their values to be exact) are being serialized into [u8]. While very generic, this is not what many potential users can expect when serializing into text formats like JSON. Serializing values into string (same as header names) may be more practical.

**Comment by nox** [comment]
Header values are not always string, so this is not safe to do. I would accept a PR that uses `str::from_utf8` to optionally serialize each `Vec<u8>` returned by `Headers::get_raw` as a string, though.

**Comment by imp** [comment]
What exactly do you mean by optionally serialize ? Like attempts to serialize into `String` and otherwise leaves as `Vec<u8>` ?

**Comment by nox** [comment]
Yes. Something like:

```rust
match str::from_utf8(header_value) {
    Some(str) => serializer.serialize_str(str),
    None => serializer.serialize_bytes(header_value),
}
```

**Comment by nox** [comment]
@dtolnay Can you think of any serde format that wouldn't cope with that?

**Comment by dtolnay** [comment]
Some data formats may require you to know which one you serialized as. In general you can't do `serializer.serialize_bytes(...)` and then `deserializer.deserialize_string(...)` and expect it to work.

Maybe you could serialize it as a newtype variant? I don't know whether this is any better than the current approach.

```rust
match str::from_utf8(header_value) {
    Ok(s) => serializer.serialize_newtype_variant("Header", 0, "string", s),
    Err(_) => serializer.serialize_newtype_variant("Header", 1, "bytes", header_value),
}
```

**Comment by nox** [comment]
Yeah no that wouldn't produce the optimal JSON either.

@imp Two questions:

* Would that be ok if we still serialise as an array of things, but said things are strings this time? E.g.:

```json
{"Connection":["close"]}
```

* Would that be ok if I don't change the default behaviour to keep bincode fast, but provide a function `serialize_utf8` that does the `str::from_utf8` call during serialisation?

**Comment by imp** [comment]
@nox I believe second approach is best. Thanks for considering it!

**Comment by nox** [comment]
@imp Can you confirm that the code in https://github.com/nox/hyper_serde/pull/8 fits your needs?

**Comment by imp** [comment]
@nox Works pretty well. Although I am not sure I understand why it is important to serialize into a list of one single String, rather than one String item itself. Probably I am missing something fundamental here...

**Comment by nox** [comment]
@imp Some `Serializer` implementations have no way to know what is serialised without being told by the `Serialize` impl. E.g. `bincode`. So you can't encode some stuff as a single string, and some other stuff as a sequence of strings.

**Comment by imp** [comment]
@nox I admit I don't know too much about `bincode`. However, when I am serializing `Headers` to JSON am I wrong when I expect it to be
```
{
  "Server": "nginx"
}
```
rather than
```
{
  "Server": ["nginx"]
}
```

**Comment by nox** [comment]
@imp There is nothing wrong with a request with:

```
Server: hello
Server: world
```

From HTTP's POV it doesn't make a lot of sense, but we still have to parse that correctly, that's why headers' values are sequences.

**Comment by nox** [comment]
#8 landed and published.
